export const mockBooks = [
  {
    id: 1,
    title: 'Cánh Rồng Thứ Tư',
    author: 'Rebecca Yarros',
    price: 420000,
    genre: 'Khoa học viễn tưởng & Fantasy',
    coverUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Violet Sorrengail hai mươi tuổi đáng lẽ phải vào Đội Ghi Chép, sống một cuộc sống yên tĩnh giữa sách vở và lịch sử. Giờ đây, vị tướng chỉ huy—còn được gọi là người mẹ cứng rắn của cô—đã ra lệnh cho Violet tham gia vào hàng trăm ứng cử viên phấn đấu để trở thành tinh hoa của Navarre: kỵ sĩ rồng.',
    isbn: '978-1649374042',
    pages: 498,
    publisher: 'Nhà xuất bản Trẻ',
    language: 'Tiếng Việt',
    rating: 4.5,
    reviews: 12847,
    inStock: true
  },
  {
    id: 2,
    title: 'Ngọn Lửa Thép',
    author: 'Rebecca Yarros',
    price: 450000,
    genre: 'Khoa học viễn tưởng & Fantasy',
    coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Mọi người đều mong đợi Violet Sorrengail chết trong năm đầu tiên tại Trường Chiến tranh Basgiath. Cả Violet cũng vậy. Nhưng Threshing chỉ là bài kiểm tra bất khả thi đầu tiên nhằm loại bỏ những kẻ yếu đuối, không xứng đáng và không may mắn.',
    isbn: '978-1649374172',
    pages: 623,
    publisher: 'Nhà xuất bản Trẻ',
    language: 'Tiếng Việt',
    rating: 4.7,
    reviews: 9234,
    inStock: true
  },
  {
    id: 3,
    title: 'Bệnh Nhân Im Lặng',
    author: 'Alex Michaelides',
    price: 299000,
    genre: 'Trinh thám',
    coverUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Cuộc sống của Alicia Berenson dường như hoàn hảo. Một họa sĩ nổi tiếng kết hôn với một nhiếp ảnh gia thời trang đắt khách, cô sống trong một ngôi nhà lớn có cửa sổ nhìn ra công viên ở một trong những khu vực đáng mơ ước nhất của London. Một buổi tối, chồng cô là Gabriel về nhà muộn sau buổi chụp ảnh thời trang, và Alicia đã bắn anh ta năm phát vào mặt, sau đó không hề nói một lời nào nữa.',
    isbn: '978-1250301697',
    pages: 336,
    publisher: 'Nhà xuất bản Văn học',
    language: 'Tiếng Việt',
    rating: 4.2,
    reviews: 15632,
    inStock: true
  },
  {
    id: 4,
    title: 'Thói Quen Nguyên Tử',
    author: 'James Clear',
    price: 279000,
    genre: 'Phi hư cấu',
    coverUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Bất kể mục tiêu của bạn là gì, Thói Quen Nguyên Tử đều cung cấp một khuôn khổ đã được chứng minh để cải thiện—mỗi ngày. James Clear, một trong những chuyên gia hàng đầu thế giới về hình thành thói quen, tiết lộ các chiến lược thực tế sẽ dạy bạn chính xác cách hình thành thói quen tốt, phá vỡ thói quen xấu và làm chủ những hành vi nhỏ dẫn đến kết quả đáng chú ý.',
    isbn: '978-0735211292',
    pages: 320,
    publisher: 'Nhà xuất bản Tổng hợp TP.HCM',
    language: 'Tiếng Việt',
    rating: 4.8,
    reviews: 22451,
    inStock: true
  },
  {
    id: 5,
    title: 'Cung Điện Của Gai Và Hoa Hồng',
    author: 'Sarah J. Maas',
    price: 306000,
    genre: 'Lãng mạn',
    coverUrl: 'https://images.unsplash.com/photo-1629196914983-49d799d1461c?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Khi cô thợ săn mười chín tuổi Feyre giết một con sói trong rừng, một sinh vật đáng sợ xuất hiện để đòi bồi thường. Bị kéo đến một vùng đất ma thuật nguy hiểm mà cô chỉ biết qua truyền thuyết, Feyre phát hiện ra rằng kẻ bắt giữ cô không thực sự là một con thú, mà là một trong những yêu tinh bất tử, chết người từng cai trị thế giới của cô.',
    isbn: '978-1619634442',
    pages: 419,
    publisher: 'Nhà xuất bản Phụ nữ',
    language: 'Tiếng Việt',
    rating: 4.3,
    reviews: 18923,
    inStock: true
  },
  {
    id: 6,
    title: 'Nhà Giả Kim',
    author: 'Paulo Coelho',
    price: 239000,
    genre: 'Tiểu thuyết',
    coverUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Kiệt tác của Paulo Coelho kể câu chuyện huyền bí về Santiago, một cậu bé chăn cừu người Andalusia khao khát đi du lịch để tìm kiếm kho báu trần gian. Hành trình của cậu sẽ dẫn cậu đến những sự giàu có khác biệt—và thỏa mãn hơn nhiều—so với những gì cậu từng tưởng tượng.',
    isbn: '978-0062315007',
    pages: 208,
    publisher: 'Nhà xuất bản Hội Nhà Văn',
    language: 'Tiếng Việt',
    rating: 4.1,
    reviews: 31254,
    inStock: true
  },
  {
    id: 7,
    title: 'Bảy Người Chồng Của Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    price: 339000,
    genre: 'Tiểu thuyết',
    coverUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Biểu tượng điện ảnh Hollywood đang về già và ẩn dật Evelyn Hugo cuối cùng đã sẵn sàng nói sự thật về cuộc đời quyến rũ và gây tranh cãi của mình. Nhưng khi cô chọn phóng viên tạp chí vô danh Monique Grant cho công việc này, không ai kinh ngạc hơn chính Monique.',
    isbn: '978-1501161933',
    pages: 388,
    publisher: 'Nhà xuất bản Phụ nữ',
    language: 'Tiếng Việt',
    rating: 4.6,
    reviews: 14567,
    inStock: true
  },
  {
    id: 8,
    title: 'Dự Án Hail Mary',
    author: 'Andy Weir',
    price: 359000,
    genre: 'Khoa học viễn tưởng & Fantasy',
    coverUrl: 'https://images.unsplash.com/photo-1555116505-38ab61d5b1f6?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Ryland Grace là người sống sót duy nhất trong một nhiệm vụ tuyệt vọng, cơ hội cuối cùng—và nếu anh thất bại, nhân loại và chính trái đất sẽ diệt vong. Ngoại trừ ngay bây giờ, anh không biết điều đó. Anh thậm chí không thể nhớ tên của mình, chứ đừng nói đến bản chất của nhiệm vụ hoặc cách hoàn thành nó.',
    isbn: '978-0593135204',
    pages: 476,
    publisher: 'Nhà xuất bản Trẻ',
    language: 'Tiếng Việt',
    rating: 4.7,
    reviews: 11234,
    inStock: true
  },
  {
    id: 9,
    title: 'Thư Viện Nửa Đêm',
    author: 'Matt Haig',
    price: 319000,
    genre: 'Tiểu thuyết',
    coverUrl: 'https://images.unsplash.com/photo-1526243741027-444d633d7365?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Ở đâu đó ngoài rìa của vũ trụ có một thư viện chứa vô số cuốn sách, mỗi cuốn là câu chuyện của một thực tại khác. Một cuốn kể về cuộc đời của bạn như hiện tại, cùng với một cuốn sách khác cho cuộc sống khác mà bạn có thể đã sống nếu bạn đã đưa ra một lựa chọn khác tại bất kỳ thời điểm nào trong cuộc đời.',
    isbn: '978-0525559474',
    pages: 304,
    publisher: 'Nhà xuất bản Văn học',
    language: 'Tiếng Việt',
    rating: 4.2,
    reviews: 16789,
    inStock: true
  },
  {
    id: 10,
    title: 'Nơi Loài Hải Âu Ca Hát',
    author: 'Delia Owens',
    price: 329000,
    genre: 'Trinh thám',
    coverUrl: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Trong nhiều năm, những tin đồn về "Cô gái đầm lầy" đã ám ảnh Barkley Cove, một thị trấn yên tĩnh trên bờ biển Bắc Carolina. Vì vậy, vào cuối năm 1969, khi Chase Andrews đẹp trai được tìm thấy đã chết, người dân địa phương ngay lập tức nghi ngờ Kya Clark, cái gọi là Cô gái đầm lầy.',
    isbn: '978-0735219090',
    pages: 384,
    publisher: 'Nhà xuất bản Văn học',
    language: 'Tiếng Việt',
    rating: 4.4,
    reviews: 28456,
    inStock: true
  },
  {
    id: 11,
    title: 'Nó Kết Thúc Với Chúng Ta',
    author: 'Colleen Hoover',
    price: 319000,
    genre: 'Lãng mạn',
    coverUrl: 'https://images.unsplash.com/photo-1535666669445-e8c15cd2e7d9?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Lily không phải lúc nào cũng dễ dàng, nhưng điều đó chưa bao giờ ngăn cản cô làm việc chăm chỉ cho cuộc sống mà cô muốn. Cô đã đi một chặng đường dài từ thị trấn nhỏ nơi cô lớn lên—cô tốt nghiệp đại học, chuyển đến Boston và bắt đầu công việc kinh doanh riêng của mình.',
    isbn: '978-1501110368',
    pages: 384,
    publisher: 'Nhà xuất bản Phụ nữ',
    language: 'Tiếng Việt',
    rating: 4.5,
    reviews: 19876,
    inStock: true
  },
  {
    id: 12,
    title: 'Tư Duy Nhanh Và Chậm',
    author: 'Daniel Kahneman',
    price: 379000,
    genre: 'Phi hư cấu',
    coverUrl: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Trong tác phẩm này, Kahneman giải thích hai hệ thống thúc đẩy cách chúng ta suy nghĩ và đưa ra lựa chọn. Hệ thống 1 nhanh, trực giác và cảm xúc; Hệ thống 2 chậm hơn, có tính cân nhắc hơn và logic hơn.',
    isbn: '978-0374533557',
    pages: 499,
    publisher: 'Nhà xuất bản Thế Giới',
    language: 'Tiếng Việt',
    rating: 4.6,
    reviews: 13567,
    inStock: true
  },
  {
    id: 13,
    title: 'Harry Potter Và Hòn Đá Phù Thủy',
    author: 'J.K. Rowling',
    price: 259000,
    genre: 'Thiếu nhi',
    coverUrl: 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Harry Potter chưa bao giờ nghe nói về Hogwarts khi những bức thư bắt đầu rơi xuống chiếu cửa ở số bốn, Privet Drive. Được viết bằng mực xanh trên giấy da màu vàng với con dấu tím, chúng nhanh chóng bị tịch thu bởi dì và chú khủng khiếp của anh.',
    isbn: '978-0439708180',
    pages: 309,
    publisher: 'Nhà xuất bản Trẻ',
    language: 'Tiếng Việt',
    rating: 4.9,
    reviews: 45678,
    inStock: true
  },
  {
    id: 14,
    title: 'Đấu Trường Sinh Tử',
    author: 'Suzanne Collins',
    price: 299000,
    genre: 'Thanh thiếu niên',
    coverUrl: 'https://images.unsplash.com/photo-1551029506-0807df4e0f36?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Trong tàn tích của một nơi từng được gọi là Bắc Mỹ nằm quốc gia Panem, một Thủ đô rực rỡ được bao quanh bởi mười hai quận xa xôi. Thủ đô khắc nghiệt và tàn nhẫn và giữ các quận trong hàng ngũ bằng cách buộc tất cả phải gửi một cậu bé và một cô gái từ mười hai đến mười tám tuổi tham gia vào Đấu trường Sinh tử hàng năm, một cuộc chiến chết chóc trên truyền hình trực tiếp.',
    isbn: '978-0439023481',
    pages: 374,
    publisher: 'Nhà xuất bản Trẻ',
    language: 'Tiếng Việt',
    rating: 4.7,
    reviews: 32145,
    inStock: true
  },
  {
    id: 15,
    title: 'Percy Jackson Và Tên Trộm Tia Chớp',
    author: 'Rick Riordan',
    price: 279000,
    genre: 'Thiếu nhi',
    coverUrl: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Percy Jackson sắp bị đuổi khỏi trường nội trú... một lần nữa. Và đó là vấn đề nhỏ nhất của cậu. Gần đây, những con quái vật thần thoại và các vị thần trên đỉnh Olympus dường như đang bước thẳng ra khỏi trang sách giáo khoa thần thoại Hy Lạp của Percy và vào cuộc sống của cậu.',
    isbn: '978-0786838653',
    pages: 377,
    publisher: 'Nhà xuất bản Kim Đồng',
    language: 'Tiếng Việt',
    rating: 4.6,
    reviews: 27893,
    inStock: true
  },
  {
    id: 16,
    title: 'Lỗi Là Do Các Vì Sao',
    author: 'John Green',
    price: 289000,
    genre: 'Thanh thiếu niên',
    coverUrl: 'https://images.unsplash.com/photo-1515426913136-94d456b7a5af?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Mặc dù phép màu y học co rút khối u đã mua cho cô vài năm, Hazel chưa bao giờ là gì khác ngoài giai đoạn cuối, chương cuối cùng của cô được khắc ngay khi chẩn đoán. Nhưng khi một bước ngoặt cốt truyện tuyệt đẹp tên là Augustus Waters đột nhiên xuất hiện tại Nhóm Hỗ trợ Trẻ em Ung thư, câu chuyện của Hazel sắp được viết lại hoàn toàn.',
    isbn: '978-0525478812',
    pages: 313,
    publisher: 'Nhà xuất bản Trẻ',
    language: 'Tiếng Việt',
    rating: 4.5,
    reviews: 25678,
    inStock: true
  },
  {
    id: 17,
    title: 'Giáo Dục',
    author: 'Tara Westover',
    price: 349000,
    genre: 'Phi hư cấu',
    coverUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Tara Westover mười bảy tuổi lần đầu tiên đặt chân vào lớp học. Sinh ra trong gia đình sống sót trên núi Idaho, cô chuẩn bị cho ngày tận thế bằng cách dự trữ đào ngâm tự làm và ngủ với ba lô "đầu-lên-đồi" của mình.',
    isbn: '978-0399590504',
    pages: 334,
    publisher: 'Nhà xuất bản Thế Giới',
    language: 'Tiếng Việt',
    rating: 4.7,
    reviews: 18934,
    inStock: true
  },
  {
    id: 18,
    title: 'Trở Thành',
    author: 'Michelle Obama',
    price: 399000,
    genre: 'Phi hư cấu',
    coverUrl: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=200&h=300',
    description: 'Trong hồi ký của mình, một tác phẩm suy ngẫm sâu sắc và kể chuyện mê hoặc, Michelle Obama mời độc giả vào thế giới của mình, ghi lại những trải nghiệm đã định hình cô—từ thời thơ ấu ở South Side của Chicago đến những năm là giám đốc cân bằng các nhu cầu của vai trò làm mẹ và công việc.',
    isbn: '978-1524763138',
    pages: 448,
    publisher: 'Nhà xuất bản Thế Giới',
    language: 'Tiếng Việt',
    rating: 4.8,
    reviews: 21456,
    inStock: true
  }
]

// Dữ liệu mẫu cho giỏ hàng (dùng id từ mockBooks)
export const mockCartItems = [
  { id: 1, quantity: 2 },
  { id: 4, quantity: 1 },
  { id: 6, quantity: 1 }
]

export const mockGenres = [
  'Tiểu thuyết', 'Phi hư cấu', 'Trinh thám', 'Lãng mạn', 'Khoa học viễn tưởng & Fantasy', 'Thanh thiếu niên', 'Thiếu nhi'
]

export const mockNavItems = [
  'Sách', 'Sách điện tử', 'Sách nói', 'Thanh thiếu niên', 'Thiếu nhi'
]

export const mockFooterLinks = [
  {
    title: 'DỊCH VỤ',
    links: ['Chương trình đối tác', 'Hướng dẫn tác giả', 'Thành viên']
  },
  {
    title: 'VỀ CHÚNG TÔI',
    links: ['Giới thiệu', 'Tuyển dụng', 'Công ty']
  },
  {
    title: 'HỖ TRỢ',
    links: ['Trung tâm trợ giúp', 'Giao hàng', 'Tra cứu đơn hàng', 'Đổi trả']
  }
]
